name: 'GH Actions create Jira ticket'

on:
  workflow_dispatch:

jobs:
  tests:
    name: Cypress & Percy Tests

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Show inputs
        run: |
          echo "run_id: ${{ github.run_id }}"

  jira:
    needs: tests

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Get latest active sprint ID
        id: latest-sprint
        run: |
          response=$(curl --silent --user '${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}' \
            --header 'Accept: application/json' \
            --request GET \
            --url 'https://ce-platform.atlassian.net/rest/agile/1.0/board/2656/sprint?state=active' \
          )
          latest_sprint_id=$(echo "$response" | jq -r '.values[0].id')
          echo "LATEST_SPRINT_ID=$latest_sprint_id" >> $GITHUB_ENV

      - name: Get issue type 'Task' ID
        id: issueTypes
        run: |
          ISSUE_TYPES=$(curl --silent --user '${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}' \
            --header 'Accept: application/json' \
            --request GET \
            --url 'https://ce-platform.atlassian.net/rest/api/3/project/${{ secrets.JIRA_PROJECT_KEY }}' | jq '.issueTypes[] | {id, name}')

          TASK_ISSUE_TYPE_ID=$(echo "$ISSUE_TYPES" | jq -r 'select(.name == "Task").id')
          echo "TASK_ISSUE_TYPE_ID=$TASK_ISSUE_TYPE_ID" >> $GITHUB_ENV

      - name: Set current date
        id: set-date
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create Jira Issue
        run: |
          curl --silent --user '${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}' \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --request POST \
            --url 'https://ce-platform.atlassian.net/rest/api/3/issue' \
            --data '{
              "fields": {
                "project": {
                  "key": "${{ secrets.JIRA_PROJECT_KEY }}"
                },
                "assignee": {
                  "id": "608000ea074a0b006a77f40f"
                },
                "summary": "Review distilled sites results - ${{ steps.set-date.outputs.date }}",
                "description": {
                  "type": "doc",
                  "version": 1,
                  "content": [
                  {
                    "type": "paragraph",
                    "content":[
                        {
                          "type": "text",
                          "text": "Build URL: "
                        },
                        {
                          "type": "text",
                          "text": "insert link",
                          "marks":[
                              {
                                "type": "link",
                                "attrs":{
                                  "href": "${{ secrets.GH_BASE_URL }}/actions/runs/${{ github.run_id }}"
                                }
                              }
                          ]
                        }
                    ]
                  },
                ]
                },                
                "issuetype": {
                  "id": "${{ env.TASK_ISSUE_TYPE_ID }}"
                },
                "customfield_10007": ${{ env.LATEST_SPRINT_ID }}
              },
              "update": {}
            }'
        env:
          TASK_ISSUE_TYPE_ID: ${{ env.TASK_ISSUE_TYPE_ID }}
          LATEST_SPRINT_ID: ${{ env.LATEST_SPRINT_ID }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      
    
    