name: 'GH Actions create Jira ticket'

on:
  workflow_dispatch:

jobs:
  tests:
    name: Cypress & Percy Tests

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Show inputs
        run: |
          echo "run_id: ${{ github.run_id }}"

      - name: Get issue type 'Task' ID
        id: issueTypes
        run: |
          ISSUE_TYPES=$(curl --silent --user '${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}' \
            --header 'Accept: application/json' \
            --request GET \
            --url 'https://ce-platform.atlassian.net/rest/api/3/project/${{ secrets.JIRA_PROJECT_KEY }}' | jq '.issueTypes[] | {id, name}')

          TASK_ISSUE_TYPE_ID=$(echo "$ISSUE_TYPES" | jq -r 'select(.name == "Task").id')
          echo "TASK_ISSUE_TYPE_ID=$TASK_ISSUE_TYPE_ID" >> $GITHUB_ENV

      # - name: Create Jira Issue
      #   run: |
      #     echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      #     curl --silent --user '${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}' \
      #       --header 'Accept: application/json' \
      #       --header 'Content-Type: application/json' \
      #       --request POST \
      #       --url 'https://ce-platform.atlassian.net/rest/api/3/issue' \
      #       --data '{
      #         "fields": {
      #           "project": {
      #             "key": ${{ secrets.JIRA_PROJECT_KEY }}
      #           },
      #           "assignee": {
      #             "id": "608000ea074a0b006a77f40f"
      #           },
      #           "summary": "Review distilled sites results - ${{ env.CURRENT_DATE }}",
      #           "description": {
      #             "type": "doc",
      #             "version": 1,
      #             "content": [
      #               {
      #                 "type": "paragraph",
      #                 "content": [
      #                   {
      #                     "text": "Build URL: ${{ secrets.GH_BASE_URL }}/actions/runs/${{ github.run_id }}  ",
      #                     "type": "text"
      #                   }
      #                 ]
      #               }
      #             ]
      #           },
      #           "issuetype": {
      #             "id": "${{ env.TASK_ISSUE_TYPE_ID }}"
      #           }
      #         },
      #         "update": {}
      #       }'
      #   env:
      #     JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create Jira Issue
        run: |
          echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          json_body='{
            "fields": {
              "project": {
                "key": "'${{ secrets.JIRA_PROJECT_KEY }}'"
              },
              "assignee": {
                "id": "608000ea074a0b006a77f40f"
              },
              "summary": "Review distilled sites results - '"${{ env.CURRENT_DATE }}"'",
              "description": {
                "type": "doc",
                "version": 1,
                "content": [
                  {
                    "type": "paragraph",
                    "content": [
                      {
                        "text": "Build URL: '"${{ secrets.GH_BASE_URL }}"/actions/runs/'"${{ github.run_id }}"'",
                        "type": "text"
                      }
                    ]
                  }
                ]
              },
              "issuetype": {
                "id": "'${{ env.TASK_ISSUE_TYPE_ID }}'"
              }
            },
            "update": {}
          }'
          curl --silent --user '${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}' \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --request POST \
            --url 'https://ce-platform.atlassian.net/rest/api/3/issue' \
            --data "$json_body"
        env:
          TASK_ISSUE_TYPE_ID: ${{ env.TASK_ISSUE_TYPE_ID }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    


      # - name: Create Jira Issue
      #   run: |
      #     curl --silent --user '${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}' \
      #       --header 'Accept: application/json' \
      #       --header 'Content-Type: application/json' \
      #       --request POST \
      #       --url 'https://ce-platform.atlassian.net/rest/api/3/issue' \
      #       --data '{
      #         "fields": {
      #           "project": {
      #             "key": "UNBO"
      #           },
      #           "assignee":{
      #             "id":"608000ea074a0b006a77f40f"
      #           },
      #           "summary": "Review distilled sites results - $(date +'%Y-%m-%d')",
      #           "description": {
      #             "type": "doc",
      #             "version": 1,
      #             "content": [
      #               {
      #                 "type": "paragraph",
      #                 "content": [
      #                   {
      #                     "text": "Build URL: ${{ secrets.GH_BASE_URL }}/actions/runs/${{ github.run_id }}  ",
      #                     "type": "text"
      #                   }
      #                 ]
      #               }
      #             ]
      #           },
      #           "issuetype": {
      #             "id": "${{ env.TASK_ISSUE_TYPE_ID }}"
      #           }
      #         },
      #         "update": {}
      #       }'
      #   env:
      #     JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}