name: Triggering a workflow
on:
  workflow_dispatch:
jobs:
  trigger-build:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    name: Invoke workflow with inputs
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: reusable-workflow.yml
          # token: ${{ secrets.JIRA_REPORTER_EMAIL }}
          # inputs: '{ "name": "Name from another workflow on push", "home": "London" }'

  call-workflow-passing-data:
    uses: ./.github/workflows/gh-reusable-workflow.yml
    secrets: inherit